import { jsPDF } from "jspdf";
import "jspdf-autotable";
import companyLogo from "../assets/pdflogo.png";

export default function generatePdf(data, filename, userName, currentDate) {
  const doc = new jsPDF();
  const columns = Object.keys(data[0]);
  const tableData = data.map((item) => Object.values(item));

  // Add current date at the top right corner
  const dateFormatOptions = { day: 'numeric', month: 'long', year: 'numeric' };
  const formattedDate = currentDate.toLocaleDateString(undefined, dateFormatOptions);
  const dateX = doc.internal.pageSize.width - 30; 
  const dateY = 10;

  doc.setFontSize(8);
  doc.text(formattedDate, dateX, dateY);

  // // Add title of the report
  // const titleX = doc.internal.pageSize.width / 2;
  // const titleY = 20;
  // doc.setFontSize(14); 
  // doc.setFont('helvetica', 'bold');
  // doc.text(filename, titleX, titleY, { align: 'center' });

   // Add user name at the bottom of the page
   const footerText = `Generated by: ${userName}`;
   const footerHeight = 10;
   const footerX = 10;
   const footerY = doc.internal.pageSize.height - footerHeight;
 
   doc.setFontSize(8);
   doc.text(footerText, footerX, footerY); 
  
  // Add company logo at the top and center it
  const imgWidth = 70; 
  const imgHeight = 50; 
  const imgX = (doc.internal.pageSize.width - imgWidth) / 2;
  doc.addImage(companyLogo, 'PNG', imgX, 10, imgWidth, imgHeight);


  let startY = 40; // Adjust the starting position as needed
  doc.text(filename, 14, startY);
  startY += 10;
  doc.autoTable({
    startY,
    head: [columns],
    body: tableData,
  });
  doc.save(`${filename}.pdf`);
}
